-- MySQL Script generated by MySQL Workbench
-- 03/15/18 10:43:07
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`roles` (
  `idRoles` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRoles`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`services` (
  `idServices` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(244) NULL,
  `credential` CHAR(32) NOT NULL,
  PRIMARY KEY (`idServices`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  UNIQUE INDEX `credential_UNIQUE` (`credential` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`actions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`actions` (
  `idActions` INT NOT NULL AUTO_INCREMENT,
  `idServicesActions` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `url` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`idActions`),
  UNIQUE INDEX `Service_name_Unique` (`idServicesActions` ASC, `name` ASC),
  UNIQUE INDEX `url_UNIQUE` (`url` ASC),
  CONSTRAINT `FK_ActionsServices`
    FOREIGN KEY (`idServicesActions`)
    REFERENCES `mydb`.`services` (`idServices`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`signals`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`signals` (
  `idSignals` INT NOT NULL AUTO_INCREMENT,
  `idServicesSignals` INT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idSignals`),
  UNIQUE INDEX `Services_Signale_Unique` (`idServicesSignals` ASC, `name` ASC),
  CONSTRAINT `FK_SignalsServices`
    FOREIGN KEY (`idServicesSignals`)
    REFERENCES `mydb`.`services` (`idServices`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`conections`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`conections` (
  `idConnections` INT NOT NULL AUTO_INCREMENT,
  `idSignals` INT NOT NULL,
  `idActions` INT NOT NULL,
  PRIMARY KEY (`idConnections`),
  INDEX `FK_Actions_idx` (`idActions` ASC),
  INDEX `FK_Signals_idx` (`idSignals` ASC),
  UNIQUE INDEX `idSignals_UNIQUE` (`idSignals` ASC, `idActions` ASC),
  CONSTRAINT `FK_Signals`
    FOREIGN KEY (`idSignals`)
    REFERENCES `mydb`.`signals` (`idSignals`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Actions`
    FOREIGN KEY (`idActions`)
    REFERENCES `mydb`.`actions` (`idActions`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `idUsers` INT NOT NULL AUTO_INCREMENT,
  `idRoles` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `password` CHAR(64) NOT NULL,
  PRIMARY KEY (`idUsers`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  INDEX `FK_Roles_idx` (`idRoles` ASC),
  CONSTRAINT `FK_Roles`
    FOREIGN KEY (`idRoles`)
    REFERENCES `mydb`.`roles` (`idRoles`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users_connections`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users_connections` (
  `idUsers` INT NOT NULL,
  `idConnections` INT NOT NULL,
  `public` TINYINT(1) NULL,
  PRIMARY KEY (`idUsers`, `idConnections`),
  INDEX `FK_Connections_idx` (`idConnections` ASC),
  CONSTRAINT `FK_Users`
    FOREIGN KEY (`idUsers`)
    REFERENCES `mydb`.`users` (`idUsers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Connections`
    FOREIGN KEY (`idConnections`)
    REFERENCES `mydb`.`conections` (`idConnections`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
